/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e1bfb4",
        "outline": "#a88a80",
        "outline-variant": "#594139",
        "primary": "#ffb59b",
        "on-primary": "#5b1a00",
        "primary-container": "#ff6d33",
        "on-primary-container": "#5f1b00",
        "on-primary-fixed": "#380d00",
        "secondary": "#d6baff",
        "on-secondary": "#3c2263",
        "secondary-container": "#53397c",
        "on-secondary-container": "#c5a8f3",
        "tertiary": "#dcc841",
        "on-tertiary": "#373100",
        "tertiary-container": "#bfac26",
        "on-tertiary-container": "#484000",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "error": "#ffb4ab",
      },
    },
  },
  plugins: [],
};
